window.UOGA_STATE = {
  googleBaselineMap: null,
  cesiumViewer: null,
  huntUnitsLayer: null,
  cesiumHuntDataSource: null,
  cesiumUtahOutlineDataSource: null,
  googleApiReady: false,
  huntHoverFeature: null,
  selectedBoundaryFeature: null,
  huntData: [],
  huntBoundaryGeoJson: null,
  selectedBoundaryMatches: [],
  selectedHunt: null,
  selectionInfoWindow: null,
  usfsLayer: null,
  blmLayer: null,
  blmDetailLayer: null,
  wildernessLayer: null,
  utahOutlineLayer: null,
  sitlaLayer: null,
  stateLandsLayer: null,
  stateParksLayer: null,
  wmaLayer: null,
  cwmuLayer: null,
  privateLayer: null,
  outfitters: [],
  outfitterFederalCoverage: [],
  outfitterMarkers: [],
  activeLoads: 0,
  currentGlobeBasemap: 'esriImagery',
  outfitterMarkerRunId: 0,
  suppressLandClickUntil: 0,
  googleMapsLoadTimeoutId: null,
  conservationPermitAreas: [],
  conservationPermitHuntTable: [],
  conservationPermitAreaCodeSet: new Set(),
  conservationPermitAreaSpeciesUnitNameSet: new Set(),
  conservationPermitAreaSpeciesUnitCodeSet: new Set(),
  conservationPermitAreaAllowedTypeMap: new Map(),
  outfitterGeocodeCache: new Map(),
  outfitterMarkerIndex: new Map(),
  blmOwnershipPointCache: new Map(),
  blmDistrictPointCache: new Map(),
  outfitterFederalCoverageIndex: new Map()
};
